#!/bin/bash

# utility to sync the latest TSE Accreditation content from git

mysync() {
    syncdir=$1
    cd $syncdir && git pull
}

SUCCESS=false

while read DIR
do
    while [[ $SUCCESS == "false" ]]
    do
        mysync $DIR
        if [ $? -eq 0 ]
        then
            SUCCESS=true
        else
            SUCCESS=false
            sleep 5
        fi
    done
done < /etc/tseprep.conf

exit 0
