#!/bin/bash

# utility to sync the latest TSE Accreditation content from git

mysync() {
    syncdir=$1
    cd $syncdir && git pull
}


while read DIR
do
    SUCCESS=false
    COUNT=0
    while [[ "$SUCCESS" == "false" ]] && [ "$COUNT" -lt 10 ]
    do
        mysync $DIR
        if [ $? -eq 0 ]
        then
            SUCCESS=true
        else
            SUCCESS=false
            COUNT=$((COUNT+1))
            sleep 5
        fi
    done
done < /etc/tseprep.conf

exit 0
